package Interfaces.Templates.Process;

import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import org.omg.CORBA.UNKNOWN;

public class DirectorySelection extends javax.swing.JPanel {

    /**
     * Creates new form DirectoryConfiguration
     */
    public DirectorySelection() {
        initComponents();
        addPopUpJLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCarpetaOrigen = new javax.swing.JPanel();
        lblTituloCarpetaOrigen = new javax.swing.JLabel();
        btnBuscarCarpetaDatosOrigen = new Classes.UI.Java2D.JCustomButtom.JCustomButton();
        lblRutaCarpetaOrigen = new javax.swing.JLabel();
        panelCarpetaDestino = new javax.swing.JPanel();
        lblRutaCarpetaDestino = new javax.swing.JLabel();
        lblTituloCarpetaDestino = new javax.swing.JLabel();
        btnBuscarCarpetaDatosDestino = new Classes.UI.Java2D.JCustomButtom.JCustomButton();

        setLayout(new java.awt.GridLayout(2, 1));

        panelCarpetaOrigen.setBackground(new java.awt.Color(244, 244, 244));
        panelCarpetaOrigen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carpeta de origen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        panelCarpetaOrigen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblTituloCarpetaOrigen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTituloCarpetaOrigen.setText("Selecciona la carpeta en donde se encuentran los datos de la actualización:");

        btnBuscarCarpetaDatosOrigen.setText("Buscar");
        btnBuscarCarpetaDatosOrigen.setFocusPainted(false);
        btnBuscarCarpetaDatosOrigen.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        btnBuscarCarpetaDatosOrigen.setName("origen"); // NOI18N
        btnBuscarCarpetaDatosOrigen.setRippleColor(new java.awt.Color(153, 153, 153));
        btnBuscarCarpetaDatosOrigen.setShadowColor(new java.awt.Color(0, 0, 0));
        btnBuscarCarpetaDatosOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCarpetaDatosOrigenMouseClicked(evt);
            }
        });

        lblRutaCarpetaOrigen.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRutaCarpetaOrigen.setText("?_");

        javax.swing.GroupLayout panelCarpetaOrigenLayout = new javax.swing.GroupLayout(panelCarpetaOrigen);
        panelCarpetaOrigen.setLayout(panelCarpetaOrigenLayout);
        panelCarpetaOrigenLayout.setHorizontalGroup(
            panelCarpetaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarpetaOrigenLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCarpetaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRutaCarpetaOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCarpetaOrigenLayout.createSequentialGroup()
                        .addComponent(lblTituloCarpetaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(btnBuscarCarpetaDatosOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCarpetaOrigenLayout.setVerticalGroup(
            panelCarpetaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarpetaOrigenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCarpetaOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCarpetaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCarpetaDatosOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblRutaCarpetaOrigen)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        add(panelCarpetaOrigen);

        panelCarpetaDestino.setBackground(new java.awt.Color(244, 244, 244));
        panelCarpetaDestino.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carpeta de destino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        panelCarpetaDestino.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        lblRutaCarpetaDestino.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRutaCarpetaDestino.setText("?_");

        lblTituloCarpetaDestino.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTituloCarpetaDestino.setText("Selecciona la carpeta en donde se encuentra la carpeta a actualizar:");

        btnBuscarCarpetaDatosDestino.setText("Buscar");
        btnBuscarCarpetaDatosDestino.setFocusPainted(false);
        btnBuscarCarpetaDatosDestino.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        btnBuscarCarpetaDatosDestino.setName("destino"); // NOI18N
        btnBuscarCarpetaDatosDestino.setRippleColor(new java.awt.Color(153, 153, 153));
        btnBuscarCarpetaDatosDestino.setShadowColor(new java.awt.Color(0, 0, 0));
        btnBuscarCarpetaDatosDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarCarpetaDatosDestinoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCarpetaDestinoLayout = new javax.swing.GroupLayout(panelCarpetaDestino);
        panelCarpetaDestino.setLayout(panelCarpetaDestinoLayout);
        panelCarpetaDestinoLayout.setHorizontalGroup(
            panelCarpetaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarpetaDestinoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCarpetaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRutaCarpetaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCarpetaDestinoLayout.createSequentialGroup()
                        .addComponent(lblTituloCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(btnBuscarCarpetaDatosDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCarpetaDestinoLayout.setVerticalGroup(
            panelCarpetaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarpetaDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCarpetaDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloCarpetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCarpetaDatosDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblRutaCarpetaDestino)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        add(panelCarpetaDestino);
        panelCarpetaDestino.getAccessibleContext().setAccessibleName("Carpeta de destino en donde se colocaran los archivos de actualización");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCarpetaDatosOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCarpetaDatosOrigenMouseClicked
        selectPath(btnBuscarCarpetaDatosOrigen.getName());
    }//GEN-LAST:event_btnBuscarCarpetaDatosOrigenMouseClicked

    private void btnBuscarCarpetaDatosDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarCarpetaDatosDestinoMouseClicked
        selectPath(btnBuscarCarpetaDatosDestino.getName());
    }//GEN-LAST:event_btnBuscarCarpetaDatosDestinoMouseClicked

    private void addPopUpJLabel() {
        JPopupMenu jPopupMenuCarpetaOrigen = createPopupMenu("origen");
        JPopupMenu jPopupMenuCarpetaDestino = createPopupMenu("destino");

        jPopupMenuCarpetaOrigen.setLightWeightPopupEnabled(false);
        jPopupMenuCarpetaDestino.setLightWeightPopupEnabled(false);

        panelCarpetaOrigen.setComponentPopupMenu(jPopupMenuCarpetaOrigen);
        panelCarpetaDestino.setComponentPopupMenu(jPopupMenuCarpetaDestino);
    }

    private JPopupMenu createPopupMenu(String type) {
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem jmiMostrarTodos = new JMenuItem("Seleccionar ruta de " + type);
        jmiMostrarTodos.setToolTipText("Selecciona la ruta de " + type);
        jmiMostrarTodos.addActionListener(e -> selectPath(type));
        popupMenu.add(jmiMostrarTodos);

        JMenuItem jmiMostrarCarpeta = new JMenuItem("Copiar la ruta al portapapeles");
        jmiMostrarCarpeta.setToolTipText("Copea la ruta del directorio de la carpeta de " + type + " en tu portapapeles");
        jmiMostrarCarpeta.addActionListener(e -> copyPath(type));
        popupMenu.add(jmiMostrarCarpeta);

        return popupMenu;
    }

    private void selectPath(String type) {
        String path = Classes.Core.IO.Files.getSelectedDirectoryPath();
        if (path.isEmpty()) {
            return;
        }

        switch (type) {
            case "origen":
                lblRutaCarpetaOrigen.setText(path);
                Classes.Core.App.Cache.setOripath(path);
                break;
            case "destino":
                lblRutaCarpetaDestino.setText(path);
                Classes.Core.App.Cache.setDespath(path);
                break;
            default:
                throw new UnsupportedOperationException("Invalid operation");
        }
    }

    private void copyPath(String type) {
        switch (type) {
            case "origen":
                String oriPath = Classes.Core.App.Cache.getOripath();
                if(oriPath != null)
                    Classes.Core.Utilities.ClipboardUtil.copyTextToClipboard(oriPath);
                break;
            case "destino":
                String desPath = Classes.Core.App.Cache.getDespath();
                if(desPath != null)
                    Classes.Core.Utilities.ClipboardUtil.copyTextToClipboard(desPath);
                break;
            default:
                throw new UnsupportedOperationException("Invalid operation");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Classes.UI.Java2D.JCustomButtom.JCustomButton btnBuscarCarpetaDatosDestino;
    private Classes.UI.Java2D.JCustomButtom.JCustomButton btnBuscarCarpetaDatosOrigen;
    private javax.swing.JLabel lblRutaCarpetaDestino;
    private javax.swing.JLabel lblRutaCarpetaOrigen;
    private javax.swing.JLabel lblTituloCarpetaDestino;
    private javax.swing.JLabel lblTituloCarpetaOrigen;
    private javax.swing.JPanel panelCarpetaDestino;
    private javax.swing.JPanel panelCarpetaOrigen;
    // End of variables declaration//GEN-END:variables
}
