package Interfaces.Templates.Process;

import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

public class End extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public End() {
        initComponents();
        writeText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();
        panelInferior = new javax.swing.JPanel();
        btnSalir = new Classes.UI.Java2D.JCustomButtom.JCustomButton();

        setBackground(new java.awt.Color(244, 244, 244));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(244, 244, 244));
        texto.setBorder(null);
        texto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto.setDoubleBuffered(true);
        texto.setFocusable(false);
        jScrollPane1.setViewportView(texto);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelInferior.setBackground(new java.awt.Color(244, 244, 244));
        panelInferior.setPreferredSize(new java.awt.Dimension(100, 84));

        btnSalir.setBackground(new java.awt.Color(0, 143, 90));
        btnSalir.setForeground(new java.awt.Color(250, 250, 250));
        btnSalir.setText("Salir");
        btnSalir.setFocusPainted(false);
        btnSalir.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        btnSalir.setRippleColor(new java.awt.Color(0, 66, 41));
        btnSalir.setShadowColor(new java.awt.Color(0, 143, 90));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                .addContainerGap(652, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(panelInferior, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked


    private void writeText() {
        StyledDocument doc = texto.getStyledDocument();

        // Estilos
        Style estiloGrande = texto.addStyle("Grande", null);
        StyleConstants.setFontSize(estiloGrande, 24);

        try {
            doc.insertString(doc.getLength(), "Proceso de actualización concluido\n\n", estiloGrande);
            doc.insertString(doc.getLength(), "El proceso de actualización del software SIAD ha terminado ya puedes cerrar esta herramienta", null);
        } catch (BadLocationException e) {
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Classes.UI.Java2D.JCustomButtom.JCustomButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
