package Interfaces.Templates.Process;

import java.awt.Color;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        writeText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(244, 244, 244));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(244, 244, 244));
        texto.setBorder(null);
        texto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto.setDoubleBuffered(true);
        texto.setFocusable(false);
        jScrollPane1.setViewportView(texto);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void writeText() {
        StyledDocument doc = texto.getStyledDocument();

        // Estilos
        Style estiloNegrita = texto.addStyle("Negrita", null);
        StyleConstants.setBold(estiloNegrita, true);
        Style estiloRojo = texto.addStyle("Rojo", null);
        StyleConstants.setForeground(estiloRojo, Color.RED);
        Style estiloGrande = texto.addStyle("Grande", null);
        StyleConstants.setFontSize(estiloGrande, 24);

        try {
            doc.insertString(doc.getLength(), "Hola de nuevo\n\n", estiloGrande);
            doc.insertString(doc.getLength(), "Bienvenido al asistente para la actualización de ", null);
            doc.insertString(doc.getLength(), " SIAD", estiloNegrita);
            doc.insertString(doc.getLength(), ". Es altamente recomendable que lea con atención la serie de pasos que se te presentarán a lo largo del recorrido de la actualización.\n\n", null);
            doc.insertString(doc.getLength(), "Además, tienes la posibilidad de regresar entre los pasos si es que no estás seguro de alguna configuración que ingresaste, siempre y cuando sea posible.", null);
            
        } catch (BadLocationException e) {
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
