package Interfaces.Templates;

import Classes.UI.Java2D.JGlassPanelPopUp.JGlassPanePopup;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import java.net.URI;

public class InfoTemplate extends javax.swing.JPanel {

    /**
     * Creates new form InfoTemplate
     */
    public InfoTemplate() {
        initComponents();
        writeText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblNombrePrograma = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        panelDerecho = new javax.swing.JPanel();
        btnAceptar = new Classes.UI.Java2D.JCustomButtom.JCustomButton();
        lblDesarrollador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();

        setMinimumSize(new java.awt.Dimension(980, 454));
        setPreferredSize(new java.awt.Dimension(980, 454));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.setPreferredSize(new java.awt.Dimension(843, 65));
        panelSuperior.setLayout(new java.awt.BorderLayout());

        lblNombrePrograma.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        lblNombrePrograma.setForeground(new java.awt.Color(80, 80, 80));
        lblNombrePrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePrograma.setText("Acerca de SIAD-UPDATER");
        panelSuperior.add(lblNombrePrograma, java.awt.BorderLayout.CENTER);

        add(panelSuperior, java.awt.BorderLayout.NORTH);

        panelContenedor.setBackground(new java.awt.Color(244, 244, 244));
        panelContenedor.setLayout(new java.awt.BorderLayout());

        panelDerecho.setBackground(new java.awt.Color(244, 244, 244));
        panelDerecho.setPreferredSize(new java.awt.Dimension(160, 373));

        btnAceptar.setText("Aceptar");
        btnAceptar.setFocusPainted(false);
        btnAceptar.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        btnAceptar.setRippleColor(new java.awt.Color(153, 153, 153));
        btnAceptar.setShadowColor(new java.awt.Color(0, 0, 0));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });

        lblDesarrollador.setForeground(new java.awt.Color(80, 80, 80));
        lblDesarrollador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesarrollador.setText("Jhovany J.");
        lblDesarrollador.setToolTipText("Desarrolador:");

        javax.swing.GroupLayout panelDerechoLayout = new javax.swing.GroupLayout(panelDerecho);
        panelDerecho.setLayout(panelDerechoLayout);
        panelDerechoLayout.setHorizontalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblDesarrollador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelDerechoLayout.setVerticalGroup(
            panelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDerechoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(lblDesarrollador)
                .addContainerGap())
        );

        panelContenedor.add(panelDerecho, java.awt.BorderLayout.EAST);

        jScrollPane1.setBorder(null);

        texto.setEditable(false);
        texto.setBackground(new java.awt.Color(244, 244, 244));
        texto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        texto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        texto.setFocusable(false);
        jScrollPane1.setViewportView(texto);

        panelContenedor.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(panelContenedor, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        JGlassPanePopup.closePopup("Info");
    }//GEN-LAST:event_btnAceptarMouseClicked

    @Override
    protected void paintComponent(Graphics graphics) {
        Graphics2D graphics2D = (Graphics2D) graphics.create();
        graphics2D.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        graphics2D.setColor(getBackground());
        graphics2D.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 10, 10));
        graphics2D.dispose();
        super.paintComponent(graphics);
    }

  private void writeText() {
        StyledDocument doc = texto.getStyledDocument();

        // Estilos
        Style estiloNegrita = texto.addStyle("Negrita", null);
        StyleConstants.setBold(estiloNegrita, true);
        Style estiloRojo = texto.addStyle("Rojo", null);
        StyleConstants.setForeground(estiloRojo, Color.RED);
        Style estiloAzul = texto.addStyle("Azul", null);
        StyleConstants.setForeground(estiloAzul, Color.BLUE);
        StyleConstants.setUnderline(estiloAzul, true);  // Agregamos subrayado
        Style estiloGrande = texto.addStyle("Grande", null);
        StyleConstants.setFontSize(estiloGrande, 24);

        try {
            doc.insertString(doc.getLength(), "Acerca de este programa:\n", estiloGrande);
            doc.insertString(doc.getLength(), "SIAD-UPDATER", estiloNegrita);
            doc.insertString(doc.getLength(), " es un software encargado de automatizar la tarea de ", null);
            doc.insertString(doc.getLength(), "actualización", estiloRojo);
            doc.insertString(doc.getLength(), " del software ", null);
            doc.insertString(doc.getLength(), "SIAD", estiloNegrita);
            doc.insertString(doc.getLength(), " propietario de ", null);
            doc.insertString(doc.getLength(), "CFE", estiloNegrita);
            doc.insertString(doc.getLength(), ", todo esto a modo de realizar esta tarea tan tediosa de manera más sencilla. Cabe aclarar que este software ", null);
            doc.insertString(doc.getLength(), "NO", estiloRojo);
            doc.insertString(doc.getLength(), " realiza tareas de configuración de los datos de la aplicación ni alguna otra tarea adicional.\n\n", null);
            doc.insertString(doc.getLength(), "Acerca de la aplicación:\n", estiloGrande);
            doc.insertString(doc.getLength(), "Versión de la aplicación: ", null);
            doc.insertString(doc.getLength(), "v1.0\n", estiloNegrita);
            doc.insertString(doc.getLength(), "Fecha de versión: ", null);
            doc.insertString(doc.getLength(), "2024/11/13\n", estiloNegrita);
            doc.insertString(doc.getLength(), "Documentación de la aplicación: ", null);
            doc.insertString(doc.getLength(), "https://github.com/DonGabriel87/SIAD-UPDATER", estiloAzul);
        } catch (BadLocationException e) {
            e.printStackTrace();
        }

        // Obtener la posición donde se insertó el texto del enlace
        final int linkStart = doc.getLength() - "github.com/example".length();
        final int linkEnd = doc.getLength();

        // Añadir el evento de clic al enlace
        texto.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    int offset = texto.viewToModel(e.getPoint());  // Usamos viewToModel
                    if (offset >= linkStart && offset <= linkEnd) {
                        // Si el clic está dentro del rango del enlace
                        Desktop.getDesktop().browse(new URI("https://github.com/DonGabriel87/SIAD-UPDATER"));
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Classes.UI.Java2D.JCustomButtom.JCustomButton btnAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesarrollador;
    private javax.swing.JLabel lblNombrePrograma;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelDerecho;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTextPane texto;
    // End of variables declaration//GEN-END:variables
}
