package Interfaces.Templates;

import java.awt.event.MouseListener;

public class StartUpTemplate extends javax.swing.JPanel {

    public StartUpTemplate(MouseListener ml) {
        initComponents();
        btnComenzar.addMouseListener(ml);
        btnConfiguraciones.addMouseListener(ml);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComenzar = new Classes.UI.Java2D.JCustomButtom.JCustomButton();
        btnConfiguraciones = new Classes.UI.Java2D.JCustomButtom.JCustomButton();

        setBackground(new java.awt.Color(244, 244, 244));
        setName("StartUpTemplate"); // NOI18N

        btnComenzar.setBackground(new java.awt.Color(0, 143, 90));
        btnComenzar.setForeground(new java.awt.Color(250, 250, 250));
        btnComenzar.setText("Comenzar");
        btnComenzar.setFocusCycleRoot(true);
        btnComenzar.setFocusPainted(false);
        btnComenzar.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        btnComenzar.setName("StartUpTemplate - Comenzar"); // NOI18N
        btnComenzar.setRippleColor(new java.awt.Color(0, 66, 41));
        btnComenzar.setShadowColor(new java.awt.Color(0, 143, 90));

        btnConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/icono-informacion.png"))); // NOI18N
        btnConfiguraciones.setFocusPainted(false);
        btnConfiguraciones.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        btnConfiguraciones.setName("StartUpTemplate - Info"); // NOI18N
        btnConfiguraciones.setPreferredSize(new java.awt.Dimension(64, 64));
        btnConfiguraciones.setRippleColor(new java.awt.Color(0, 0, 0));
        btnConfiguraciones.setShadowColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfiguraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(btnConfiguraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Classes.UI.Java2D.JCustomButtom.JCustomButton btnComenzar;
    private Classes.UI.Java2D.JCustomButtom.JCustomButton btnConfiguraciones;
    // End of variables declaration//GEN-END:variables
}
